variable "image_description" {
  type    = string
  default = "ubuntu-nginx-${env("USER")}"
}

variable "folder_id" {
  type    = string
  default = "${env("YC_FOLDER")}"
}

variable "service_account_key_file" {
  type    = string
  default = "${env("YC_KEYFILE")}"
}

# "timestamp" template function replacement
locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "yandex" "autogenerated_1" {
  disk_type                = "network-ssd"
  folder_id                = var.folder_id
  image_description        = var.image_description
  image_family             = "ubuntu-web-server"
  image_name               = "ubuntu-2004-lts-nginx-${local.timestamp}"
  platform_id              = "standard-v2"
  source_image_family      = "ubuntu-2004-lts"
  ssh_username             = "ubuntu"
  service_account_key_file = var.service_account_key_file
  use_ipv4_nat             = true
}

build {
  sources = ["source.yandex.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "echo 'updating apt cache'",
      "sudo apt update -y",
      "sudo apt install -y nginx nano git",
      "sudo systemctl enable nginx",
      "curl localhost"
    ]
  }

}
